# Generated by Django 4.1.1 on 2022-09-25 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_movie_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='like',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
